build:
  main: cmd/apex/main.go
  binary: apex
  env:
    - CGO_ENABLED=0
  flags: -trimpath
  ldflags: -s -w -X github.com/hchonan/apex/cmd/apex/version.Version={{.Tag}} -buildid=
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
